-- MySQL Script generated by MySQL Workbench
-- 05/30/16 15:58:44
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Titulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Titulo` (
  `idTitulo` INT NOT NULL AUTO_INCREMENT,
  `nomeTitulo` VARCHAR(45) NOT NULL,
  `sinopseTitulo` TEXT(500) NULL,
  PRIMARY KEY (`idTitulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Idioma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Idioma` (
  `idIdioma` INT NOT NULL,
  `nomeIdioma` VARCHAR(45) NOT NULL,
  `regiaoIdioma` VARCHAR(45) NULL,
  `siglaIdioma` VARCHAR(5) NULL,
  PRIMARY KEY (`idIdioma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Audio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Audio` (
  `idAudio` INT NOT NULL AUTO_INCREMENT,
  `FK_video` INT NOT NULL,
  `descricaoAudio` VARCHAR(45) NOT NULL,
  `caminhoAudio` VARCHAR(45) NOT NULL,
  `FK_idioma` INT NULL,
  PRIMARY KEY (`idAudio`, `FK_video`),
  INDEX `FK_video_idx` (`FK_video` ASC),
  INDEX `FK_idioma_idx` (`FK_idioma` ASC),
  CONSTRAINT `FK_video`
    FOREIGN KEY (`FK_video`)
    REFERENCES `mydb`.`Video` (`idVideo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_idioma`
    FOREIGN KEY (`FK_idioma`)
    REFERENCES `mydb`.`Idioma` (`idIdioma`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Video` (
  `idVideo` INT NOT NULL AUTO_INCREMENT,
  `caminhoVideo` VARCHAR(45) NOT NULL,
  `FK_audioOriginal` INT NULL,
  PRIMARY KEY (`idVideo`),
  INDEX `FK_audio_idx` (`FK_audioOriginal` ASC),
  CONSTRAINT `FK_audio`
    FOREIGN KEY (`FK_audioOriginal`)
    REFERENCES `mydb`.`Audio` (`idAudio`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Filme` (
  `FK_titulo` INT NOT NULL,
  `FK_video` INT NULL,
  PRIMARY KEY (`FK_titulo`),
  UNIQUE INDEX `FK_titulo_UNIQUE` (`FK_titulo` ASC),
  INDEX `FK_video_idx` (`FK_video` ASC),
  CONSTRAINT `FK_titulo`
    FOREIGN KEY (`FK_titulo`)
    REFERENCES `mydb`.`Titulo` (`idTitulo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_video`
    FOREIGN KEY (`FK_video`)
    REFERENCES `mydb`.`Video` (`idVideo`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Serie` (
  `FK_titulo` INT NOT NULL,
  PRIMARY KEY (`FK_titulo`),
  UNIQUE INDEX `FK_titulo_UNIQUE` (`FK_titulo` ASC),
  CONSTRAINT `FK_titulo`
    FOREIGN KEY (`FK_titulo`)
    REFERENCES `mydb`.`Titulo` (`idTitulo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
KEY_BLOCK_SIZE = 1;


-- -----------------------------------------------------
-- Table `mydb`.`Temporada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Temporada` (
  `FK_serie` INT NOT NULL,
  `idTemporada` INT NOT NULL,
  `nomeTemporada` VARCHAR(45) NULL,
  `sinopseTemporada` TEXT(500) NULL,
  PRIMARY KEY (`FK_serie`, `idTemporada`),
  CONSTRAINT `fk_table1_Serie1`
    FOREIGN KEY (`FK_serie`)
    REFERENCES `mydb`.`Serie` (`FK_titulo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Episodio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Episodio` (
  `FK_serie` INT NOT NULL,
  `FK_temporada` INT NOT NULL,
  `idEpisodio` INT NOT NULL,
  `nomeEpisodio` VARCHAR(45) NULL,
  `sinopseEpisodio` TEXT(500) NULL,
  `FK_video` INT NULL,
  PRIMARY KEY (`FK_serie`, `FK_temporada`, `idEpisodio`),
  INDEX `FK_video_idx` (`FK_video` ASC),
  INDEX `fk_Episodio_Temporada1_idx` (`FK_serie` ASC, `FK_temporada` ASC),
  CONSTRAINT `FK_video`
    FOREIGN KEY (`FK_video`)
    REFERENCES `mydb`.`Video` (`idVideo`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `FK_temporada`
    FOREIGN KEY (`FK_serie` , `FK_temporada`)
    REFERENCES `mydb`.`Temporada` (`FK_serie` , `idTemporada`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Legenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Legenda` (
  `idLegenda` INT NOT NULL AUTO_INCREMENT,
  `FK_video` INT NOT NULL,
  `descricaoLegenda` VARCHAR(45) NOT NULL,
  `caminhoLegenda` VARCHAR(45) NOT NULL,
  `FK_idioma` INT NULL,
  PRIMARY KEY (`idLegenda`, `FK_video`),
  INDEX `FK_video_idx` (`FK_video` ASC),
  INDEX `FK_idioma_idx` (`FK_idioma` ASC),
  CONSTRAINT `FK_video`
    FOREIGN KEY (`FK_video`)
    REFERENCES `mydb`.`Video` (`idVideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_idioma`
    FOREIGN KEY (`FK_idioma`)
    REFERENCES `mydb`.`Idioma` (`idIdioma`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `nomeUsuario` VARCHAR(45) NOT NULL,
  `emailUsuario` VARCHAR(45) NOT NULL,
  `loginUsuario` VARCHAR(45) NOT NULL,
  `senhaUsuario` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Preferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Preferencias` (
  `FK_usuario` INT NOT NULL,
  `preferirAudioOriginal` TINYINT(1) NOT NULL,
  `FK_idiomaNativo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`FK_usuario`),
  INDEX `FK_idioma_idx` (`FK_idiomaNativo` ASC),
  CONSTRAINT `FK_usuario`
    FOREIGN KEY (`FK_usuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_idioma`
    FOREIGN KEY (`FK_idiomaNativo`)
    REFERENCES `mydb`.`Idioma` (`idIdioma`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Idiomas_Conhecidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Idiomas_Conhecidos` (
  `FK_preferencias` INT NOT NULL,
  `FK_idioma` INT NOT NULL,
  PRIMARY KEY (`FK_preferencias`, `FK_idioma`),
  INDEX `FK_idioma_idx` (`FK_idioma` ASC),
  CONSTRAINT `FK_preferencias`
    FOREIGN KEY (`FK_preferencias`)
    REFERENCES `mydb`.`Preferencias` (`FK_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_idioma`
    FOREIGN KEY (`FK_idioma`)
    REFERENCES `mydb`.`Idioma` (`idIdioma`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico` (
  `FK_Usuario` INT NOT NULL,
  `FK_Titulo` INT NOT NULL,
  `horaHistorico` DATETIME NOT NULL,
  PRIMARY KEY (`FK_Usuario`, `FK_Titulo`),
  INDEX `FK_titulo_idx` (`FK_Titulo` ASC),
  CONSTRAINT `FK_usuario`
    FOREIGN KEY (`FK_Usuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_titulo`
    FOREIGN KEY (`FK_Titulo`)
    REFERENCES `mydb`.`Titulo` (`idTitulo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Historico_Reproducao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Historico_Reproducao` (
  `FK_usuario` INT NOT NULL,
  `FK_titulo` INT NOT NULL,
  `FK_video` INT NOT NULL,
  `FK_configAudio` INT NULL,
  `FK_configLegenda` INT NULL,
  `posicaoArquivo` TIME NOT NULL,
  PRIMARY KEY (`FK_usuario`, `FK_titulo`, `FK_video`),
  INDEX `FK_video_idx` (`FK_video` ASC),
  INDEX `FK_idioma_idx` (`FK_configAudio` ASC, `FK_configLegenda` ASC),
  CONSTRAINT `FK_historico`
    FOREIGN KEY (`FK_usuario` , `FK_titulo`)
    REFERENCES `mydb`.`Historico` (`FK_Usuario` , `FK_Titulo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_video`
    FOREIGN KEY (`FK_video`)
    REFERENCES `mydb`.`Video` (`idVideo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_idioma`
    FOREIGN KEY (`FK_configAudio` , `FK_configLegenda`)
    REFERENCES `mydb`.`Idioma` (`idIdioma` , `idIdioma`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
